### ISSUE TITLE
CLI capitalized in the word "client", maybe a find and replace gone wrong 

### ISSUE THREAD

**Issue by ode-to-the-code** [learn-co-curriculum/rails-application-basics-readme#13]
vendor – this directory has been utilized for varying purposes in the past. In Rails 4+, its main purpose is for integrating CLIent-side MVC frameworks, such as AngularJS.

**Comment by drakeltheryuujin** [comment]
We have updated the materials and believe this issue has been resolved. Thanks for your contribution!
