### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by JuanGongora** [learn-co-curriculum/rails-application-basics-readme#14]
Line 110 reads:

- **app** – contains the models, views, and controllers, along with the the rest

Should be:

- **app** – contains the models, views, and controllers, along with the rest

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe this issue has been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
