### ISSUE TITLE
rake db:create Doesn't work

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/rails-application-basics-readme#15]
Hey there, when I ran the command `rake db:create` I got a huge list of errors (mostly bootstrap and its dependency on nokogiri.) The only way I was able to get the server to work was to use `rails generate model user` add information to the migration, then `rake db:migrate`. I don't know if other students have encountered the same problem, but it took a thirty minute call with a coach to figure it out.

Best,
A

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
