### ISSUE TITLE
Doesn't explicitly say to clone the repo

### ISSUE THREAD

**Issue by BenitolSantos** [learn-co-curriculum/rails-application-basics-readme#16]
"Yep, that's the problem. You have to fork and then clone down the repo to your local computer and be inside of it" - Johnathan Chriest May 10, 2019 11:28am EST

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm unable to reproduce or decipher if this is related to this README, so I'm going to close it for now. If this is related to this lesson, could you provide a bit more detail about the issue?
Thanks! 💙
