### ISSUE TITLE
Confusing Directions

### ISSUE THREAD

**Issue by Madeline-Stark** [learn-co-curriculum/rails-application-basics-readme#17]
Under "Generating A New Rails Application", it has students create a new rails app, but does not explicitly tell them to cd into the app and open it in their text editor. This is confusing for some students and will cause issues when they try to run rake db:create.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe this issue has been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
