### ISSUE TITLE
Turn off rails server before starting console (missing)

### ISSUE THREAD

**Issue by alexcrisan** [learn-co-curriculum/rails-application-basics-readme#7]
Just wanted to point out that after the part it tells us to start the Rails server using "rails s" it then tells us to run the console using "rails c" but doesn't mention stopping the server first using Ctrl + c. I think this detail would make the instructions more clear.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
